[package]
name = "i3lock-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
fast_image_resize = { version = "5.1.3", features = [ "image" ] }
image = "0.25.6"
imageproc = "0.25.0"
stb_image = "0.3.0"
x11 = "2.21.0"
